# Generated by Django 4.2.23 on 2025-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('region', models.CharField(blank=True, choices=[('Taipei', 'Taipei'), ('Netherlands', 'Netherlands')], max_length=255, null=True)),
                ('image', models.ImageField(upload_to='events/%Y/%m')),
                ('is_special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
