# Generated by Django 4.2.23 on 2025-08-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReviews',
            new_name='BookReview',
        ),
    ]
